### PR TITLE
feat:add carousel effect for metric banner in smaller screen

### LINKED ISSUE #131: Implement Carousel for Multiple Sections in Mobile View
To enhance mobile user experience, we need to implement a carousel for the following sections: Banner, Upcoming Events, Recent Events, Project, Member, and Brand. This will allow users to swipe through these sections easily on smaller screens, improving accessibility and engagement. The carousel should be responsive and maintain functionality across different mobile devices.

### PR DESCRIPTION
**Pull request by aayush105**
**Title:** Implement Carousel Effect for Metrics Banner

**Description:**  
This PR introduces a carousel effect for the metrics banner component. Previously static, the metrics now dynamically cycle, enhancing user engagement.
Also resolves #131 for metric section only.

**Key Changes:**
- Added carousel functionality for key metrics.
- On smaller screen: displays 1 metric at a time.

---

### Before and After Preview

**Before:**  
- Static display of metrics without interactivity.

Screenshot 2024-10-25 145003

**After:**  
- Dynamic carousel showcasing metrics, improving engagement.

https://github.com/user-attachments/assets/5bd24e50-4190-4e2e-b544-fd84e000ecab

This update enhances the responsiveness and interactivity of the metrics banner. Please review and provide feedback. Thank you!

### CODE REVIEW

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Comment by prabhavpokharel** [comment]
Maybe make it swipeable or just lessen the display duration for individual metrics by 0.5 or 1 second.

**Comment by aayush105** [comment]
The changing duration is set to 5 sec as of now if it looks slow, i can make it to 3 sec. should i try it?
@prabhavpokharel @BISHALTWR

**Comment by prabhavpokharel** [comment]
Yeah, do it.

**Comment by BISHALTWR** [comment]
Yes 3s should look good.

**Comment by aayush105** [comment]
I have updated it to the 3s now. 
can you check it? @prabhavpokharel @BISHALTWR

**Comment by prabhavpokharel** [comment]
Looks better

**Review by prabhavpokharel — APPROVED** [review]
LGTM!

**Review by BISHALTWR — APPROVED** [review]
Looks good now ✨✨

**Pull request merged**
