### PR TITLE
enhance: add assets and fix banner width in events page

### PR DESCRIPTION
**Pull request by prabhavpokharel**
### Summary of changes
1. Removed dummy upcoming and past events.
2. Added a square thumbnail image and a horizontal banner image to every event. Hence, also addresses #78. 
3. Replaced the event date with the correct one.
4. Made the event description width equal to the banner width for consistency.

### Preview
image
image

### CODE REVIEW

**Review by BISHALTWR — APPROVED** [review]
Looks good

**Comment by gaurovgiri** [comment]
I think it might be better if we create folder for each event. What do you think @prabhavpokharel and @BISHALTWR ?

**Comment by rpandox** [comment]
I also think what @gaurovgiri said is better
the folder structure is something like this
assets/images/events/automationWithPython2024
@prabhavpokharel @BISHALTWR What do yoy think

**Comment by BISHALTWR** [comment]
Yeah, that is better. Let's do that.

**Comment by prabhavpokharel** [comment]
Can you give me the number of photos planned to be in the individual event folder? This information will help me think and create a better organizational structure for files and folders. @gaurovgiri

**Comment by rpandox** [comment]
I am thinking of 5 to 10 photos each 

As we dont have proper gallery section we could do this after adding gallery section and show 5-10 photos from each event and add latest photos in the gallery

**Comment by gaurovgiri** [comment]
Not sure exactly how many to add but suppose if we want add other images related to a event, we can organize those images in a folder.
We can name images with number like assets/images/events/<some_event>/{1.png, 2.png, 3.png, thumbnail.png, banner.png}
we can later add gallery list in the front matter for each markdown such that it is easier to apply loop and display those images in our gallery.

Let's create an issue on this for now.

**Comment by prabhavpokharel** [comment]
I updated the folder structure, let me know how it is! @gaurovgiri @rpandox

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Comment by gaurovgiri** [comment]
@prabhavpokharel, you may merge it by yourself.

**Pull request merged**
