### PR TITLE
Event layout update

### LINKED ISSUE #101: Abnormal image shape in events page
Here's how the image looks now.
image

### LINKED ISSUE #104: Use different image for event cards thumbnail and detail page
- Use different image here:
image

- and here:
image

### PR DESCRIPTION
**Pull request by BISHALTWR**
- Closes #104 
- Made some changes for #101 but i think the page requires some redesign from @prabhavpokharel Closes #101

- This is how it looks after changes:
image

### CODE REVIEW

**Comment by BISHALTWR** [comment]
Also, some references for anchor tags were changed.

**Comment by prabhavpokharel** [comment]
Sure, I will look into that.

**Review by prabhavpokharel — APPROVED** [review]
I think we should work on this further when the assets have been gathered.

**Comment by BISHALTWR** [comment]
Yeah lets do that

**Review by gaurovgiri — APPROVED** [review]
This looks good to me. We should start looking for the assets.

**Pull request merged**
