### PR TITLE
feat: add event layout

### LINKED ISSUE #55: [FEAT!] Event Layout is missing
Event Layout seems to be missing. This layout will be used to display the content for individual event.

You might face Issue no #54. If you can work around it then it's awesome else, just display the content and leave it without styling the content part.

### PR DESCRIPTION
**Pull request by gaurovgiri**
This PR resolves #55.

### Changes:
- _config.yml: Updated permalink structure for event collections.
- Add Event Layout
- Add some some dummy events for now.
  

### Output
Screenshot 2024-10-12 at 5 42 46 PM

The content part of the event can be manually styled in the markdown file, which gives flexibility for the content to be displayed the way we want.

Feel free to suggest any changes.

### CODE REVIEW

**Review by BISHALTWR — APPROVED** [review]
Looks good.

**Review by BISHALTWR — CHANGES_REQUESTED** [review]
- I just noticed this redundancy in content of event card, can you look at it?
This

**Comment by gaurovgiri** [comment]
Found the problem! @rpandox 👀
Screenshot 2024-10-13 at 12 16 03 PM

**Review by rpandox — APPROVED** [review]
Sorry For That

Looks Good To Me Now!!

**Review by BISHALTWR — APPROVED** [review]
Looks good.

**Pull request merged**
