### PR TITLE
enhance: update hero section with carousel and enhanced layout

### LINKED ISSUE #142: Revamp Hero Section with Carousel & Enhanced Layout
The hero section on the homepage needs an upgrade to improve user engagement and streamline the code structure. This issue covers separating the hero section into its own file, adding a background image carousel, and introducing clearer CTAs.

### PR DESCRIPTION
**Pull request by prabhavpokharel**
Fixes #142 

### Summary:
This PR revamps the hero section with improved interactivity and modular design.

### Key Changes:
1. **Modularization**: Moved the hero section from `home.html` to `hero-section.html` for better maintainability.
2. **Carousel Integration**: Added a 7-image background carousel using Flowbite's Tailwind CSS Carousel component ([Flowbite Carousel Docs](https://flowbite.com/docs/components/carousel/)).
3. **CTA Buttons**: Introduced two clear call-to-action buttons for streamlined user navigation.
4. **Tagline Addition**: Added a tagline to reinforce the brand message.

Before:
image

After:
https://github.com/user-attachments/assets/ddf273bf-9e7d-44e9-a117-f5f33d1b011d

### CODE REVIEW

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Screenshot 2024-10-30 at 10 36 30 AM

Upcoming Events is overlaying on the banner, can you check what might be the issue.

**Comment by prabhavpokharel** [comment]
@gaurovgiri can you check now?

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Review by BISHALTWR — APPROVED** [review]
That looks good.

**Pull request merged**
