### PR TITLE
add: project section

### LINKED ISSUE #73: [ADD]: A project section
Add this project section under the recent event section. 

image

P.S: After adding this section the home page will be complete.

### PR DESCRIPTION
**Pull request by rpandox**
### Summary

- Adds the Project Section in the main code {hard-coded}
- Adds all the icon thouht that can be needed in assets
- Makes the Project Section Responsive
- resolves #73 

### Output:-
- **Large Screens**

Screenshot 2024-10-15 at 5 30 29 PM

- **Small Screens**

Screenshot 2024-10-15 at 5 30 17 PM

### CODE REVIEW

**Review by BISHALTWR — CHANGES_REQUESTED** [review]
The card looks amazing but I have some suggestions:

-  Use open source UI libraries (i can think of font awesome and materialui over the top of my head) for icons instead of adding that to project assets. We can't possibly add every tool and language available out there.
- As you mentioned this is hard-coded, this needs to be changed.. maybe with a different PR.

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Agreeing here with @BISHALTWR.
Few suggestions from me:
- the buttons and tags here donot match completely with the design, you can check `tailwind buttons` for reference
- this seems hardcoded, you should start working by creating _projects collection and create dynamic content.
- Also I think we should add Projects in NavBar. I'm writing this because if in future, computer club starts doing research based projects, it will be good show all of them and separate out categories as well.

**Comment by gaurovgiri** [comment]
@rpandox Currently, I suggest to close this PR, or remove all those assets and as suggested by @BISHALTWR use some third party library that provides logos through CDN, I suggest to use `iconify`. Also it would be easy later if you could create a `tech-logo.yml` inside `_data` where logos are defined as:

```yaml
html: logos:html
fastapi: simple-icon:fast-api
```

and later under `_projects` collection for a project you can directly mention the list of tech in front-matter by
`tech: [html, fastapi]`
and then render the logo in for loop.

**Comment by rpandox** [comment]
ok!!
i will open this again!

**Pull request closed without merging**
