### PR TITLE
feat: add nav bar contets, images, dropdown

### LINKED ISSUE #15: Implement Responsive Navbar with Logo, Navigation Links, and Contact Button
Create a navbar with a logo on the left, navigation links on the right.

### PR DESCRIPTION
**Pull request by SamratAdhikari**
image

This PR will resolve #15 

### Changes:

- Added navbar contents
- Added dropdown menu for Events
- Added logo

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@SamratAdhikari I have a suggestion for improving the navbar UI. We could consider adding a subtle visual change for the selected item, such as changing its color or adding an underline (e.g., when "Home" is selected make this nav item different than others). This could help distinguish the active item and enhance the overall navigation experience.

Feel free to explore this and see if it improves the look.

**Review by BISHALTWR — COMMENTED** [review]
- Dropdown UI doesn't match the design
    - Plan
        image
    - Current
        image

**Comment by SamratAdhikari** [comment]
> * Dropdown UI doesn't match the design
>   
>   * Plan
>     image
>   * Current
>     image


These changes were made in the latest pull request.

**Comment by SamratAdhikari** [comment]
> @SamratAdhikari I have a suggestion for improving the navbar UI. We could consider adding a subtle visual change for the selected item, such as changing its color or adding an underline (e.g., when "Home" is selected make this nav item different than others). This could help distinguish the active item and enhance the overall navigation experience.
> 
> Feel free to explore this and see if it improves the look.

I will start working on distinguishing the active page from the rest immediately. Thanks

**Comment by SamratAdhikari** [comment]
### Changes: 
- **Active Page Color**: Implemented `base-black` color for the active page.
- **Responsive Design**: Improved the responsiveness of the navigation bar to ensure better display across various screen sizes.

### Issues: 
- **Hover Effects**: Jekyll variables are not functional with some effects, hence the decision to hardcode hex values for hover states. (open to suggestions)
- **Medium Screen Responsiveness**: The design is not quite responsive for a few medium sized screens.

### Output:
image
image

**Review by aayush105 — APPROVED** [review]

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Review by RakeshPandey0 — APPROVED** [review]
Great Work

**Comment by gaurovgiri** [comment]
Going for merge

**Review by BISHALTWR — COMMENTED** [review]
nice

**Pull request merged**
