### PR TITLE
Added files for blog page

### PR DESCRIPTION
**Pull request by ajogseneca**
## Main Changes
- Added new layout page for blog in _layouts folder.
- Added 3 sample post based on the figma design in _post folder.
- Added 3 images from figma, under assests/images/blog

## Screen shot of the page 
image

Let me know if any changes or improvements are required !
- This PR is associated with issue #95

### CODE REVIEW

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
This looks amazing. But few changes are required here:
- for all the blogs markdown file, add `layout: default`.
- also add some dummy content for each blog
- sort the blogs according to the date. Meaning that the recent blog should be seen first.

**Comment by ajogseneca** [comment]
@gaurovgiri Thank you for the feedback, I have added the requested changes !

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Excerpt should be small. By adding dummy content, I meant to add it after bottom line
---
layout: default
...
...
...
___

after bottom line, add the content here.
You may verify if the content gets displayed by clicking the read more button after adding the content for that blog.

**Review by prabhavpokharel — CHANGES_REQUESTED** [review]
Making the whole blog card clickable would be great I guess. Also, the title of the page is not matching with the site's theme color. Check the other pages for reference.

**Comment by ajogseneca** [comment]
## Changes
- Now blog card only show Excerpt, whole blog is in the next page
- Made the whole card clickable
- Made the title color to match with other pages
- Updated `nav.html` to support asset management. `src="{{ site.baseurl }}/assets/images/logo.png"` (This fixed an issue of logo not showing up ion redirected blog pages)


My suggestion we can create a new issue for the redirected blog page, if yes i can create the issue and work on it.

Let me know regarding these changes .

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Review by prabhavpokharel — APPROVED** [review]
Good work!

**Review by BISHALTWR — CHANGES_REQUESTED** [review]
- Could you make the size of cards equal?
image

**Comment by ajogseneca** [comment]
## Changes
- FIxed the card sizing issue by adding css and Truncate the excerpt to the first 10 words so cards can maintain uniform size

@BISHALTWR Let me know if this commit works

**Comment by ajogseneca** [comment]
Thank you guys for the approvals and feedbacks, Looking forward to contribute more !

**Pull request merged**
