### PR TITLE
fix: enhance the code readability and extraction

### LINKED ISSUE #35: Commands are wrapped with inline code; not looking pretty
Screenshot 2024-10-05 at 9 58 23 PM

instead of using inline code, use code block in `README.md`.

### PR DESCRIPTION
**Pull request by prabhavpokharel**
This PR resolves #35. 

This makes it easier to extract and read the code from the README.md file for contributors.

### CODE REVIEW

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
add the word "bash" (without double quotes) right after opening triple backticks without spaces. It will add syntax highlighting.

**Comment by prabhavpokharel** [comment]
Got it, will do it.

**Review by gaurovgiri — APPROVED** [review]
Awesome! Looks good to me.

**Review by rpandox — APPROVED** [review]
Good to GO

**Pull request merged**
