### PR TITLE
docs: add naming conventions for commit message and branch name

### PR DESCRIPTION
**Pull request by prabhavpokharel**
This PR introduces guidelines for the Git branch and commit message naming conventions in the KEC Computer Club repository. It aims to improve clarity and organization in our collaboration.

Addresses Issues #7 and #8 by providing a standardized approach for naming.

PS: Feedback is appreciated!

### CODE REVIEW

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Could you rename the filename. Same name with capitalized letters.
`NAMING-CONVENTION.md

**Comment by prabhavpokharel** [comment]
Done!

**Review by gaurovgiri — APPROVED** [review]
Awesome work! Good to go!

**Review by rpandox — APPROVED** [review]
LGTM!!!

**Review by aayush105 — APPROVED** [review]
LGTM !!!

**Comment by gaurovgiri** [comment]
This resolves #7 and #8.

**Pull request merged**
