### PR TITLE
KEC Lite page added

### LINKED ISSUE #79: [ADD: ] KEC Lite Page
```py
None
```

### PR DESCRIPTION
**Pull request by BISHALTWR**
- Don't merge before this: (Done)
    - Number of participants needs to be changed
 
 - In recent events: 
Recent

- The page:
Event page

Closes #79 
> Added option to design entire page manually if desired.

### CODE REVIEW

**Comment by BISHALTWR** [comment]
Number of participants was updated in latest commit.

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
The idea for manual layout is good, but can you rename the attribute to something self-descriptive such as `use_default_layout`/`default_layout` or `use_custom_layout`/`custom_layout`.
Also rename the markdown to `kec-lite.markdown` so that kec-lite can be simply accessed through `/events/kec-lite`. It can be done through adding a permalink attribute in the front-matter for the markdown but it's better just to rename the whole markdown will make it look unique among other events.

**Comment by BISHALTWR** [comment]
Refactored code based on suggestions in latest commit.

**Review by gaurovgiri — APPROVED** [review]
Awesome!

**Review by prabhavpokharel — APPROVED** [review]
Great!

**Pull request merged**
