### PR TITLE
Added fix for issue #118

### PR DESCRIPTION
**Pull request by ajogseneca**
## Changes 
This PR address the issue #118

## Additions
- Created a `Add to calendar button template` which has the code to get the details of the events and allows the user to download the file. I made this as a template so that it can be reused.
- Next change is in `event.html` where the Calendar Button component is added so that when user clicks in the card the download link is available there too.
- Next change is in `upcoming-events.markdown` so this is the card in which shows the glance of the event the add to calendar options is also avail;bel;e in this page so that users can directly add the event from their.

## Screenshot of .ics in action
image

### CODE REVIEW

**Review by rpandox — APPROVED** [review]
Looks Good to me !!
Thanks for contributing @ajogseneca

**Review by BISHALTWR — CHANGES_REQUESTED** [review]
- Time of event doesn't seem to match.
Can you look into it @ajogseneca 
image

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Screenshot 2024-10-25 at 1 07 34 PM
Also could you add the button in the card as well.

**Comment by aayush105** [comment]
Also there is a conflict in the event.html, can you fix it? @ajogseneca

**Comment by ajogseneca** [comment]
## Changes
- Added "add to calendar options in the home page"
- Fixed the conflicts
- Checked if the event is giving the right time when ics file is imported 
image
image

**Comment by prabhavpokharel** [comment]
The `add to calendar` button you've added in the homepage's event section is not working like the `add to calendar` button inside the individual event's page. Can you fix that?

**Comment by aayush105** [comment]
image

Hello @ajogseneca,

Could we adjust the button layout in this section to display in a row orientation on larger screens for a cleaner look, while maintaining a column orientation on mobile views? Additionally, the “Add to Calendar” button is currently experiencing some issues—could you please resolve that?

Also, as a design improvement, it might be better to style the “Add to Calendar” button with an outline bordered style or different approach which will make button distinguishable in both home page and event page. This would help distinguish it visually, as having both buttons in the same color feels a bit too uniform.

**Comment by ajogseneca** [comment]
## Changes
- As per requested made the button in a single row.
- Made changes to distinguish colors of buttons.
- Now the button in home screen is clickable and downloads the `.ics`.

Please let me know if there is any suggestion for button colors, borders or hover colors.
image

``` <!-- Add to Calendar Button Component -->
<a href="data:text/calendar;charset=utf8,BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//YourSite//EventCalendar//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:{{ uid }}
DTSTART:{{ start_date }}
{% if end_date %}
DTEND:{{ end_date }}
{% endif %}
SUMMARY:{{ title }}
DESCRIPTION:{{ description }}
LOCATION:{{ location }}
URL:{{ url }}
END:VEVENT
END:VCALENDAR" download="{{ title | slugify }}.ics">
  <button
    class="inline-block bg-yellow-500 text-white font-semibold px-4 py-2 rounded-lg hover:bg-red-800 transition-colors duration-300">
    Add to Calendar
  </button>
</a>
 ```
This is the code for button, if you guys have any suggestion for the color please let me know ! Thank you again for reviewing the changes.

**Comment by prabhavpokharel** [comment]
No, don't use the same color bg. The add to calendar button should have an orange border, the same color as that orange button. Maybe see this to get an idea about the buttons: 
https://github.com/user-attachments/assets/c943fd1e-b616-45e1-9aef-97bd14feda79

ps: do not go after the icons in the buttons

**Review by BISHALTWR — APPROVED** [review]
LGTM now. 
Thank you for taking the time to contribute.

**Comment by ajogseneca** [comment]
> LGTM now. Thank you for taking the time to contribute.

Thank you so much for your time as well !

**Review by rpandox — APPROVED** [review]
LGTM!!
Thanks for Contributing!!

**Comment by ajogseneca** [comment]
@gaurovgiri can you check your review again, thankyou !

**Review by gaurovgiri — APPROVED** [review]
LGTM!

**Pull request merged**
