### PR TITLE
fix: make nav bar responsive and uniform text size

### LINKED ISSUE #46: [FIX] The responsiveness in NAV bar is not working properly as it should
When the screen size is changes there is a point which the navbar is not functioning as it should

https://github.com/user-attachments/assets/0adec4a4-74b8-465f-861c-aa1361063de7

### PR DESCRIPTION
**Pull request by prabhavpokharel**
### Summary of changes:
- Fixed the breakdown of `Contact us` button on smaller screens.
- Made all the font-size uniform as the website font-size.
- Also, fixes #46 & #64 

### Before:
https://github.com/user-attachments/assets/2aa8aba6-9db9-4891-9971-2b345ddbaee6

### After: 
https://github.com/user-attachments/assets/eb4fa6d6-e42a-4e60-84b7-64bc94dff31a

### CODE REVIEW

**Comment by prabhavpokharel** [comment]
I would love to work on it. Thanks for the feedback!

**Comment by prabhavpokharel** [comment]
Before:
image

After: 
image

**Comment by prabhavpokharel** [comment]
Open to suggestions

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
To make the selected page more distinguishable, adding bold as font-weight will do some good. After that the PR looks good for merge.

**Comment by aayush105** [comment]
> To make the active page more distinguishable, adding bold as font-weight will do some good. After that the PR looks good for merge.

I was about to tell the same thing.

**Comment by prabhavpokharel** [comment]
Sure, will look into that!

**Comment by prabhavpokharel** [comment]
Before:
image

After:
image

**Review by aayush105 — APPROVED** [review]
Now its distinguishable. 
LGTM!!!

**Review by gaurovgiri — APPROVED** [review]
Awesome work! Going for merge!

**Pull request merged**
