### PR TITLE
fix: upcoming event layout to center if 1 event else grid

### LINKED ISSUE #50: Events listing seems to display a single event on left.
Mostly, there will be single upcoming events, so rather than giving a constant value to the `grid-col`, using condition to check if the number of `completed: false` is 1.

Possible Solution:
 To assign variable before entering the loop and increment in each loop, and according to the assigned variable changed the `grid-col`.

## Current: 
Screenshot 2024-10-06 at 4 44 10 PM

## Expected:
Screenshot 2024-10-06 at 4 51 01 PM

### PR DESCRIPTION
**Pull request by aayush105**
This pr resolves #50 

**PR Title:** Fix Events Layout for Single Upcoming Event

**Description:**
- Adjusted events listing layout for single upcoming event.
- Used conditional rendering based on the number of `completed: false` events.
- If only one event, it is centered and dix the height and width of the card.
- For multiple events, used a 2-column grid layout.
- Also fix the height and width of the image with responsive way.

**Previous:**

image

**Now:**

Screenshot 2024-10-08 224844

### CODE REVIEW

**Review by BISHALTWR — APPROVED** [review]
LGTM

**Comment by prabhavpokharel** [comment]
The card gets stretched out when viewed on smaller screens. Can you verify it once?

**Comment by gaurovgiri** [comment]
Screenshot 2024-10-09 at 8 29 12 PM
This is what @prabhavpokharel might be talking about. @aayush105 can you fix this.

**Comment by aayush105** [comment]
> Screenshot 2024-10-09 at 8 29 12 PM This is what @prabhavpokharel might be talking about. @aayush105 can you fix this.

Screenshot 2024-10-09 205623


Fixed @prabhavpokharel  and @gaurovgiri 
check it once!!!

**Review by gaurovgiri — APPROVED** [review]
kada 🔥

**Comment by prabhavpokharel** [comment]
Looks good!

**Pull request merged**
