### PR TITLE
Added fixes for issue #128

### PR DESCRIPTION
**Pull request by ajogseneca**
## Changes made
- So as requested all the indication for the year has been removed from the home screen, now home screen only shows the the active members list.
- Second thing is a new `executive-members-list` file has been added,  making it easy to modify the list of members in upcoming years.

### CODE REVIEW

**Comment by ajogseneca** [comment]
## Changes
- Added the toggle feature which existed in home screen to about us page for cleaner user experience.

**Comment by aayush105** [comment]
LGTM !!!

**Review by gaurovgiri — APPROVED** [review]
Awesome work @ajogseneca

**Comment by ajogseneca** [comment]
@gaurovgiri can we merge this, i think one more approval is needed for this, Thanks guy for the comments !

**Comment by gaurovgiri** [comment]
Sure, I will approve this.

**Pull request merged**
