### PR TITLE
feat: add executive members section

### LINKED ISSUE #57: [FEAT] Add Members Section
Executive Members section is required. It requires storing the information of Members in yaml file for each year. and displaying them as follow:

Screenshot 2024-10-06 at 11 50 30 PM

### PR DESCRIPTION
**Pull request by aayush105**
This PR resolves #57 

### Output:

image

image

### CODE REVIEW

**Review by prabhavpokharel — APPROVED** [review]
Looks awesome!

**Review by rpandox — CHANGES_REQUESTED** [review]
the card looks more like a box then a card
can you change the aspect ratio

look below for reference

373969343-cccefcb1-3e4e-440b-8cb8-98be88a1d071

**Comment by aayush105** [comment]
> the card looks more like a box then a card can you change the aspect ratio
> 
> look below for reference
> 
> 373969343-cccefcb1-3e4e-440b-8cb8-98be88a1d071

image

Is this ok sir? @rpandox

**Review by gaurovgiri — APPROVED** [review]
Looking Great!

**Review by rpandox — APPROVED** [review]
LGTM!!

**Pull request merged**
