### PR TITLE
fix: update the layout for single event in recent events section

### PR DESCRIPTION
**Pull request by gaurovgiri**
This PR is follow up for #50 for `Recent Events Section`

## Changes

- Filters Completed Events and  sort them  according to the dates
- Checks for the condition if the no of events is 1
- Creates the grid according to the size

## Current Look
Screenshot 2024-10-09 at 11 18 13 PM

## With this PR
Screenshot 2024-10-09 at 11 13 38 PM

### CODE REVIEW

**Review by BISHALTWR — APPROVED** [review]
Looks Beautiful To Me

**Comment by prabhavpokharel** [comment]
The event image looks distorted. Can you check that?

**Comment by gaurovgiri** [comment]
@prabhavpokharel thats because that image's doesn't have square resolution while the card defines the image in square aspect ratio. It won't be a problem if we create event banners in square and put it there.

**Comment by prabhavpokharel** [comment]
Yeah, we can do that too!

**Review by prabhavpokharel — APPROVED** [review]
LGTM!

**Pull request merged**
